### PR TITLE
Add 10/12bit RT format check

### PR DESCRIPTION
**Pull request by shawnli2**
Fix VaCreatconfig attribute check fail issue caused by missing some 10/12bit RT format

Signed-off-by: Shawn Li <shawn.li@intel.com>

### CODE REVIEW

**Comment by XinfengZhang** [comment]
@uartie is it ok to you?

**Comment by uartie** [comment]
This patch fails to compile for me:
```
In file included from test_va_api_fixture.h:29,
                 from test_va_api_get_max_values.cpp:25:
test_data.h:162:7: error: stray ‘\302’ in program
 static const BitMasks g_vaRTFormats = {
       ^
test_data.h:162:8: error: stray ‘\240’ in program
 static const BitMasks g_vaRTFormats = {
        ^
<snip... error repeats on other lines, too>
```

It seems your editor is inserting strange characters for spaces/tabs... Please fix your file editor and update the patch.

**Comment by shawnli2** [comment]
Thanks Artie.
New commit has updated and fixed this strange spaces.

Shawn

**Comment by uartie** [comment]
Thanks.  LGTM

**Pull request merged**
