### PR TITLE
Add lock for VA-API calls in av1encode

### PR DESCRIPTION
**Pull request by greenjustin**
Add a lock around calls to VA-API functions. A VA-API context cannot be safely accessed from multiple threads concurrently, so we need to synchronize calls to VA-API functions. Without this patch, av1encode will sometimes produce a corrupted bitstream when syncmode is disabled.

### CODE REVIEW

**Comment by greenjustin** [comment]
This patch seems to fix bitstream corruption issues I've observed on my Rex.

**Comment by XinfengZhang** [comment]
are you mean there are an thread issue with backend driver. from https://github.com/intel/libva/blob/master/va/va.h#L136-L156
backend media driver should follow this context based thread safe.

**Comment by greenjustin** [comment]
That comment says in the following paragraph:

>  * Thread-safety in this context means that when VAAPI is being called by multiple
 * concurrent threads, it will not crash or hang the OS, and VAAPI internal
 * data structures will not be corrupted. When multiple threads are operating on
 * the same VAAPI objects, it is the application's responsibility to synchronize
 * these operations in order to generate the expected results. For example, using
 * a single VAContext from multiple threads may generate unexpected results.

av1encode currently accesses VAContext from multiple threads, which is explicitly not guaranteed to produce correct results.

**Comment by XinfengZhang** [comment]
the issue already been addressed. a WA https://github.com/intel/media-driver/pull/1705 , official fix is under review and will be  posted soon

**Comment by leyu-yao** [comment]
Official fix is already merge to master. https://github.com/intel/media-driver/commit/2b40e2730

**Pull request closed without merging**
