### PR TITLE
vainfo: add VA_RC_TCBRC to reported caps list

### PR DESCRIPTION
**Pull request by dvrogozh**
Signed-off-by: Dmitry Rogozhkin <dmitry.v.rogozhkin@intel.com>

### CODE REVIEW

**Review by XinfengZhang — APPROVED** [review]

**Comment by hmaarrfk** [comment]
Where is the constant declared? This is causing compliation issues over at conda-forge

**Comment by hmaarrfk** [comment]
```
Making install in vainfo
make[1]: Entering directory `$SRC_DIR/vainfo'
  CC       vainfo-vainfo.o
vainfo.c: In function 'show_config_attributes':
vainfo.c:186:8: error: 'VA_RC_TCBRC' undeclared (first use in this function); did you mean 'VA_RC_CBR'?
  186 |       {VA_RC_TCBRC,           "VA_RC_TCBRC"},
      |        ^~~~~~~~~~~
      |        VA_RC_CBR
vainfo.c:186:8: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [vainfo-vainfo.o] Error 1
make[1]: Leaving directory `$SRC_DIR/vainfo'
make: *** [install-recursive] Error 1

```

https://github.com/conda-forge/libva-utils-feedstock/pull/16

for reference

**Comment by hmaarrfk** [comment]
sorry for the noise. for some reason the build is pullin libva 2.9. nothing for you to do

**Comment by XinfengZhang** [comment]
it is better to add VA_CHECK_VERSION to avoid build issue. will add it in future

**Pull request merged**
