### PR TITLE
[Encode] Fix issue incorrect color for EU based hevcencode

### PR DESCRIPTION
**Pull request by Tianhaol**

### CODE REVIEW

**Comment by Tianhaol** [comment]
Could you help to review this PR?

**Review by XinfengZhang — COMMENTED** [review]
all of these change is default value, does it take effect for both VME and VDEnc?

**Comment by Tianhaol** [comment]
> all of these change is default value, does it take effect for both VME and VDEnc?

Yes, they will impact VME and VDENC.  These values for these parameters are appropriate for VDENC and VME.
If there are any concerns, please let me know.

**Comment by XinfengZhang** [comment]
> > all of these change is default value, does it take effect for both VME and VDEnc?
> 
> Yes, they will impact VME and VDENC. These values for these parameters are appropriate for VDENC and VME. If there are any concerns, please let me know.

I just wonder why these default value could work on VME previously?

**Review by XinfengZhang — APPROVED** [review]

**Comment by Tianhaol** [comment]
@XinfengZhang , Do I need to update branch or rebase it?

**Pull request merged**
