### PR TITLE
Add avc sample decoder and give sample code for how to use avc streamout

### PR DESCRIPTION
**Pull request by Jexu**

### CODE REVIEW

**Comment by sreerenjb** [comment]
Would it be possible to treat StreamOutData as a part of VA-API in LibVA with some generalizations similar to FEI? If it is too much Intel specific, we can still keep it under a new directory "va/intel"..

**Comment by Jexu** [comment]
@sreerenjb It would be fine to add it in va/intel, because it is definition for hardware

**Comment by sreerenjb** [comment]
Then I recommend creating a new ISSUE against libva proposing the new API.

**Comment by Jexu** [comment]
will add sample code in open source driver, so close this pr

**Pull request closed without merging**
