### PR TITLE
X11 is never used, so don't include the headers

### PR DESCRIPTION
**Pull request by kanghuaz**
1. Fix sfcsample dx11 can't compile issue. id#150
~~2. Dump both decode and downscaled surface~~

### CODE REVIEW

**Comment by uartie** [comment]
Why did you resubmit "sample code for decode SFC" patch again?  It looks like you need to rebase with  master branch before submitting "Fix issue 150" patch.

**Comment by uartie** [comment]
Also, "Fix issue 150" is not a good commit message

**Comment by uartie** [comment]
> Also, "Fix issue 150" is not a good commit message

A better message would explain exactly what you're doing in the commit.  When a user looks at the commit message it should be obvious what the commit does (see https://github.com/intel/libva-utils/blob/master/CONTRIBUTING.md).  Of course, you can mention the issue number in a commit message but it should be treated, well, like a citation if you will.

http://chris.beams.io/posts/git-commit/ is good advice.

Also, it seems this commit should be split into two separate commits since you're addressing two different things.

**Comment by kanghuaz** [comment]
just removed the include header for dx11.
and add a new surface dump for legacy decode

**Comment by uartie** [comment]
How about:

patch 1:
```
sfcsample: don't include X11 headers

X11 is never used, so don't include the headers.

Fixes #150 

Signed-off-by: <your name/email here>
```

patch 2:
```
sfcsample: dump decoded surface

In addition to dumping the downscaled
sfc surface, dump the decoded surface, too,
so <insert why>

Signed-off-by: <your name/email here>
```

**Comment by uartie** [comment]
Your commit message still does not comply.

https://github.com/intel/libva-utils/blob/master/CONTRIBUTING.md

**Comment by uartie** [comment]
Merged as 7be46f017caee2a23097bc8371f2fe4eb1b677a0.  I also updated commit message to comply with contributing guidelines.

**Pull request closed without merging**
